In [2]:
import numpy as np

In [4]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

The main object is the homogenous multidimensional array. The dimensions are called axes.  
Eg: Coordinates of a point in 3D space = `[1, 2, 3]`. This has one axis.  
Eg: this array [[1., 0., 0.], [0., 1., 2.]] has 2 axes.

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [10]:
a.dtype, a.dtype.name

(dtype('int32'), 'int32')

itemsize is the size in bytes of each element of the array

In [11]:
a.itemsize

4

In [12]:
print(f'size of the array: {a.size}')

size of the array: 15


In [14]:
type(a)

numpy.ndarray

In [15]:
b = np.array([1, 2, 3])
type(b)

numpy.ndarray

In [16]:
b.dtype

dtype('int32')

In [18]:
x = np.array([1.2, 2.3, 3.4])
x.dtype

dtype('float64')

In [22]:
b = np.array([(1.2, 2, 3.1), (1.3, 4, 5)])
b

array([[1.2, 2. , 3.1],
       [1.3, 4. , 5. ]])

In [23]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

#### Create arrays of known shape

In [24]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [27]:
np.empty((2, 3))

array([[1.2, 2. , 3.1],
       [1.3, 4. , 5. ]])

#### Create sequences

In [29]:
np.arange(start=10, stop=30, step=5)

array([10, 15, 20, 25])

In [30]:
np.arange(0, 2, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

With `arange`, its not possible to predict the number of elements with floating point arguments. This is due to finite floating point precision. Its better to use `linspace` that takes in the number of elements we want, as an argument.  

In [34]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [38]:
x = np.linspace(0, 2*np.pi, 100)
np.sin(x)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [39]:
 a = np.arange(6)
 a2 = a[np.newaxis, :]
 a2

array([[0, 1, 2, 3, 4, 5]])